# Generated by Django 5.1.3 on 2024-11-25 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('session_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='roleassignment',
            unique_together={('user', 'room')},
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='temp_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.player'),
        ),
        migrations.AddField(
            model_name='room',
            name='temp_players',
            field=models.ManyToManyField(related_name='joined_rooms', to='myapp.player'),
        ),
        migrations.AlterUniqueTogether(
            name='roleassignment',
            unique_together={('temp_player', 'room'), ('user', 'room')},
        ),
    ]
