# Generated by Django 5.1.3 on 2024-11-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_player_alter_roleassignment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='all_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='players_ready',
            field=models.IntegerField(default=0),
        ),
    ]
